### ISSUE TITLE
Wrong documentation link in the readme?

### ISSUE THREAD

**Issue by AbbyRead** [kevinselwyn/nessemble#44]
It appears to be the wrong link in the readme.md and should be http://www.nessemble.com/documentation/

**Comment by kevinselwyn** [comment]
Thanks for bringing this to my attention! It was actually a bad subdomain redirect. This should be fixed now if you'd like to try again.

**Comment by AbbyRead** [comment]
Yep, looks good.  Thank YOU. 👍🏻
